---
title: "git_01"
author: "Connor Rice"
date: "Fall 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son! 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->

Beneath the starry sky's celestial dance,
Whispers of secrets in the night's expanse,
A moonbeam's tender touch upon the earth,
Unveils the magic of each wondrous birth.

In rhythmic harmony, the ocean's song,
Its waves embrace the shore where they belong,
As hearts entwine in love's sweet serenade,
Two souls unite, their destinies displayed.

Through valleys deep and mountains soaring high,
Life's symphony plays on, a lullaby,
Iambic beats of time, forever flow,
In nature's verse, a world to truly know.

